### ISSUE TITLE
Production build has error

### ISSUE THREAD

**Issue by natsl05164** [wmertens/compiled-i18n#1]
Hi,

There is an error "QWIK ERROR TypeError: n.map is not a function"  at production build when click any button , the "n" value is  e "_VITE_PRELOAD_" as shown in below : 
![image](https://github.com/wmertens/vite-plugin-static-i18n/assets/49542755/e8d533de-ead1-43fc-b393-24af2844ede9)

If remove compiled-i18n , the buttons will work again. 

Environment : 
"compiled-i18n": "^0.6.0"    
"@builder.io/qwik-city": "^1.2.17",
NodeJs : 20.9.0
Windows 10 

Here is repro:  
https://github.com/natsl05164/qwik-i18n-test
Prod build and serve locally  : 
npm run build.client 
npm run build.server
npm run serve

Thank you

**Comment by wmertens** [comment]
not sure what's going on here, but for sure you're not using the correct lang attribute on the container.See https://github.com/wmertens/compiled-i18n/blob/main/qwik.md

**Comment by genox** [comment]
I stumbled over something similar. Every link, be it <Link> or <a> in my prod build causes this exact error. While I do not know if this is indeed related to compiled-i18n.

The function that causes this error is Vite's preload.I tried everything, rolling back versions etc. the last ditch effort was to disable anything that might affect imports of some sort, which includes compiled-18n and this is how I ended up here.

I have the same data on that breakpoint: 
<img width="882" alt="Screenshot 2024-01-12 at 22 11 28" src="https://github.com/wmertens/compiled-i18n/assets/5611407/ae1620d6-6a32-40bd-ab6c-adbd06c0db17">

I opened (and closed) an issue over here: https://github.com/BuilderIO/qwik/issues/5706 

@wmertens let me know if I can provide any more debug information.

My app is already too big to remove every trace of compiled-i18n to verify that this is indeed the root of the issue but I'm hopeful that I found it because someone seems to have the same issue.

I followed the configuration guide to the letter. Everything should be set up properly. I will double check tho.

**Comment by genox** [comment]
For what it's worth, the only way I could fix this in time for some release is to patch vite as follows using yarn patch.

applies to vite@5.0.11

```
diff --git a/dist/node/chunks/dep-V3BH7oO1.js b/dist/node/chunks/dep-V3BH7oO1.js
index 628c10d380dd760b1f5f54baddbaa37747b335d6..f9a69bb6351276309c282d2c5c19e12778039181 100644
--- a/dist/node/chunks/dep-V3BH7oO1.js
+++ b/dist/node/chunks/dep-V3BH7oO1.js
@@ -66280,7 +66280,7 @@ function detectScriptRel() {
 function preload(baseModule, deps, importerUrl) {
     let promise = Promise.resolve();
     // @ts-expect-error __VITE_IS_MODERN__ will be replaced with boolean later
-    if (__VITE_IS_MODERN__ && deps && deps.length > 0) {
+    if (__VITE_IS_MODERN__ && deps && Array.isArray(deps) && deps.length > 0) {
         const links = document.getElementsByTagName('link');
         promise = Promise.all(deps.map((dep) => {
             // @ts-expect-error assetsURL is declared before preload.toString()

```

With this patch, production builds work and there are no more errors.

I think the root issue here is really on Vite's part, but there might be some dynamic import resulting from qwik or compiled-i18n's magic that triggers it. From digging thru various issues, seems like there are numerous cases where /* vite-ignore */ is ignored, either due to stripped comments in ts -> js transpiling or otherwise.

Maybe this helps someone who finds this in the future... patching libs is smelly as hell but as I mentioned, the main issue seems to be with vite that basically forces any import, wether configured (modulePreload: false) or not, into the preload function and uses hacks like inline comments to try and mitigate the issue.

**Comment by the-zimmermann** [comment]
@genox did you fixed it somehow?
Having the same issues right now. First only with newer vite version, but now it's also on 4.5.1.

**Comment by genox** [comment]
@the-zimmermann I got it working at some point. Upgraded to vite 5 and made sure I had no keys with "special" chars or excessive length. It has been working ever since.

**Comment by wmertens** [comment]
Yes it was an issue with the vite build in v5. Fixed it in the last commit
